version: '3'
services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - "./:/code"
    env_file:
      - "./environments/secret.env"
  front:
    build:
      context: .
      dockerfile: Dockerfile.front
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/code"