# Generated by Django 2.1.7 on 2019-02-21 00:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('actors', '0003_auto_20190219_0322'),
    ]

    operations = [
        migrations.CreateModel(
            name='BattleCombatant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.PositiveSmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SavedBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('battle_key', models.CharField(max_length=64)),
                ('combatants', models.ManyToManyField(through='simulation.BattleCombatant', to='actors.Combatant')),
            ],
        ),
        migrations.AddField(
            model_name='battlecombatant',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='simulation.SavedBattle'),
        ),
        migrations.AddField(
            model_name='battlecombatant',
            name='combatant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='actors.Combatant'),
        ),
    ]
