# Generated by Django 2.1.7 on 2020-07-27 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
        ('simulation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulatedBattle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simulated_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='SimulatedCombatant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team', models.PositiveSmallIntegerField()),
                ('battle', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='simulation.SimulatedBattle')),
                ('combatant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='actors.Combatant')),
            ],
        ),
    ]
