# Generated by Django 2.1.7 on 2019-09-13 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
