# Generated by Django 2.1.7 on 2019-02-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='is_legendary',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='action',
            name='legendary_action_cost',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
