# Generated by Django 2.1.7 on 2019-02-18 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatant',
            name='num_legendary_actions',
            field=models.SmallIntegerField(default=0),
        ),
    ]
