# Generated by Django 2.1.7 on 2019-02-19 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actors', '0002_combatant_num_legendary_actions'),
    ]

    operations = [
        migrations.AddField(
            model_name='combatant',
            name='combatant_type',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='combatant',
            name='size',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='combatant',
            name='speed',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
