name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build backend
      run: docker build -t backend  .
    - name: Build frontend
      run: docker build -t frontend -f Dockerfile.front .
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
    - name: Push backend
      run: |
        docker tag backend 446416495538.dkr.ecr.us-west-2.amazonaws.com/dnd-backend:latest
        docker push 446416495538.dkr.ecr.us-west-2.amazonaws.com/dnd-backend:latest
    - name: Push frontend
      run: |
        docker tag frontend 446416495538.dkr.ecr.us-west-2.amazonaws.com/dnd-frontend:latest
        docker push 446416495538.dkr.ecr.us-west-2.amazonaws.com/dnd-frontend:latest
  test:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v2
      - name: Test
        run: echo "Run Unit Testing"